### ISSUE TITLE
How to get the item in the cart?

### ISSUE THREAD

**Issue by Jayphen** [PregOfficial/PS5Bot-Mediamarkt#1]
Hello, I stumbled across this as I was looking to build something myself.

I see your script will log in and check if the item in the cart is available.

How is it possible to add the PS5 to the cart in the first place? Is there some trick to this?

Thanks for your help!

**Comment by PregOfficial** [comment]
Yes you could rewrite my script, if you check the PS Page (for example [Mediamarkt.at PS5](https://www.mediamarkt.at/de/product/_sony-playstation%C2%AE5-digital-1797340.html)) instead of the Cart. For example you could check if there's an Add to Cart Button.

example for Mediamarkt:
Button "In den Warenkorb" has id: pdp-add-to-cart-button
```python
# Click add to cart Button
browser.find_element_by_id('pdp-add-to-cart-button').click()
```
or you can find a Button with BeautifulSoup, which I used here: [main.py:40](https://github.com/PregOfficial/PS5Bot-Mediamarkt/blob/main/main.py#L40)

**Comment by Jayphen** [comment]
Thanks for the reply. I'll try that.

**Comment by PregOfficial** [comment]
Perfect, if you need help you can contact me.

**Comment by Jayphen** [comment]
In case you (or anyone else) is interested, here's a script I wrote that uses Playwright to check the page. Running it on a 5 min cron.

https://gist.github.com/Jayphen/14abd7caa0e02d1aef96e2d0867b25ff
